[package]
name = "DocuDodgers"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
flate2 = "1.0.27"
libc = "0.2.148"
openssl = "0.10.57"
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.107"
structopt = "0.3.26"
url = "2.4.1"
